### ISSUE TITLE
Proguard rules

### ISSUE THREAD

**Issue by michel-t-86** [spring-projects/spring-android#26]
Hi there.

I have an app that uses spring-android: 
compile 'org.springframework.android:spring-android-rest-template:1.0.1.RELEASE'

When I have ProGuard turned on during compilation, I receive a lot of warnings that makes the compilation fail. If I use -dontwarn to suppress all of them, the app builds. However, it than crashes when trying to use the library.

Below are the warnings i get:

Warning:com.fasterxml.jackson.databind.ext.DOMSerializer: can't find referenced class org.w3c.dom.bootstrap.DOMImplementationRegistry
Warning:org.springframework.http.client.CommonsClientHttpRequest: can't find referenced class org.apache.commons.httpclient.HttpMethodBase
Warning:org.springframework.http.client.CommonsClientHttpRequest: can't find referenced class org.apache.commons.httpclient.URI
Warning:org.springframework.http.client.CommonsClientHttpRequest: can't find referenced class org.apache.commons.httpclient.URIException
Warning:org.springframework.http.client.CommonsClientHttpRequest: can't find referenced class org.apache.commons.httpclient.HttpMethodBase
Warning:org.springframework.http.client.CommonsClientHttpRequest: can't find referenced class org.apache.commons.httpclient.methods.EntityEnclosingMethod
Warning:org.springframework.http.client.CommonsClientHttpRequest: can't find referenced class org.apache.commons.httpclient.methods.ByteArrayRequestEntity
Warning:org.springframework.http.client.CommonsClientHttpRequest: can't find referenced class org.apache.commons.httpclient.methods.EntityEnclosingMethod
Warning:org.springframework.http.client.CommonsClientHttpRequest: can't find referenced class org.apache.commons.httpclient.HttpClient
Warning:org.springframework.http.client.CommonsClientHttpRequest: can't find referenced class org.apache.commons.httpclient.URIException
Warning:org.springframework.http.client.CommonsClientHttpRequest: can't find referenced class org.apache.commons.httpclient.HttpMethodBase
Warning:org.springframework.http.client.CommonsClientHttpRequest: can't find referenced class org.apache.commons.httpclient.URI
Warning:org.springframework.http.client.CommonsClientHttpRequest: can't find referenced class org.apache.commons.httpclient.HttpClient
Warning:org.springframework.http.client.CommonsClientHttpRequest: can't find referenced class org.apache.commons.httpclient.HttpMethodBase
Warning:org.springframework.http.client.CommonsClientHttpRequest: can't find referenced class org.apache.commons.httpclient.HttpClient
Warning:org.springframework.http.client.CommonsClientHttpRequest: can't find referenced class org.apache.commons.httpclient.HttpMethodBase
Warning:org.springframework.http.client.CommonsClientHttpRequest: can't find referenced class org.apache.commons.httpclient.HttpClient
Warning:org.springframework.http.client.CommonsClientHttpRequest: can't find referenced class org.apache.commons.httpclient.HttpMethodBase
Warning:org.springframework.http.client.CommonsClientHttpRequest: can't find referenced class org.apache.commons.httpclient.URIException
Warning:org.springframework.http.client.CommonsClientHttpRequest: can't find referenced class org.apache.commons.httpclient.methods.EntityEnclosingMethod
Warning:org.springframework.http.client.CommonsClientHttpRequest: can't find referenced class org.apache.commons.httpclient.methods.RequestEntity
Warning:org.springframework.http.client.CommonsClientHttpRequestFactory: can't find referenced class org.apache.commons.httpclient.HttpClient
Warning:org.springframework.http.client.CommonsClientHttpRequestFactory: can't find referenced class org.apache.commons.httpclient.MultiThreadedHttpConnectionManager
Warning:org.springframework.http.client.CommonsClientHttpRequestFactory: can't find referenced class org.apache.commons.httpclient.HttpClient
Warning:org.springframework.http.client.CommonsClientHttpRequestFactory: can't find referenced class org.apache.commons.httpclient.HttpConnectionManager
Warning:org.springframework.http.client.CommonsClientHttpRequestFactory: can't find referenced class org.apache.commons.httpclient.params.HttpConnectionManagerParams
Warning:org.springframework.http.client.CommonsClientHttpRequestFactory: can't find referenced class org.apache.commons.httpclient.methods.GetMethod
Warning:org.springframework.http.client.CommonsClientHttpRequestFactory: can't find referenced class org.apache.commons.httpclient.methods.DeleteMethod
Warning:org.springframework.http.client.CommonsClientHttpRequestFactory: can't find referenced class org.apache.commons.httpclient.methods.HeadMethod
Warning:org.springframework.http.client.CommonsClientHttpRequestFactory: can't find referenced class org.apache.commons.httpclient.methods.OptionsMethod
Warning:org.springframework.http.client.CommonsClientHttpRequestFactory: can't find referenced class org.apache.commons.httpclient.methods.PostMethod
Warning:org.springframework.http.client.CommonsClientHttpRequestFactory: can't find referenced class org.apache.commons.httpclient.methods.PutMethod
Warning:org.springframework.http.client.CommonsClientHttpRequestFactory: can't find referenced class org.apache.commons.httpclient.methods.TraceMethod
Warning:org.springframework.http.client.CommonsClientHttpRequestFactory: can't find referenced class org.apache.commons.httpclient.MultiThreadedHttpConnectionManager
Warning:org.springframework.http.client.CommonsClientHttpRequestFactory: can't find referenced class org.apache.commons.httpclient.HttpConnectionManager
Warning:org.springframework.http.client.CommonsClientHttpRequestFactory: can't find referenced class org.apache.commons.httpclient.params.HttpConnectionManagerParams
Warning:org.springframework.http.client.CommonsClientHttpRequestFactory: can't find referenced class org.apache.commons.httpclient.HttpClient
Warning:org.springframework.http.client.CommonsClientHttpRequestFactory: can't find referenced class org.apache.commons.httpclient.HttpMethodBase
Warning:org.springframework.http.client.CommonsClientHttpRequestFactory: can't find referenced class org.apache.commons.httpclient.HttpConnectionManager
Warning:org.springframework.http.client.CommonsClientHttpResponse: can't find referenced class org.apache.commons.httpclient.HttpMethod
Warning:org.springframework.http.client.CommonsClientHttpResponse: can't find referenced class org.apache.commons.httpclient.Header
Warning:org.springframework.http.client.CommonsClientHttpResponse: can't find referenced class org.apache.commons.httpclient.HttpMethod
Warning:org.springframework.http.client.CommonsClientHttpResponse: can't find referenced class org.apache.commons.httpclient.Header
Warning:org.springframework.http.client.CommonsClientHttpResponse: can't find referenced class org.apache.commons.httpclient.HttpMethod
Warning:org.springframework.http.client.CommonsClientHttpResponse: can't find referenced class org.apache.commons.httpclient.Header
Warning:org.springframework.http.client.CommonsClientHttpResponse: can't find referenced class org.apache.commons.httpclient.HttpMethod
Warning:org.springframework.http.client.CommonsClientHttpResponse: can't find referenced class org.apache.commons.httpclient.Header
Warning:org.springframework.http.converter.feed.AbstractWireFeedHttpMessageConverter: can't find referenced class com.google.code.rome.android.repackaged.com.sun.syndication.io.WireFeedInput
Warning:org.springframework.http.converter.feed.AbstractWireFeedHttpMessageConverter: can't find referenced class com.google.code.rome.android.repackaged.com.sun.syndication.io.FeedException
Warning:org.springframework.http.converter.feed.AbstractWireFeedHttpMessageConverter: can't find referenced class com.google.code.rome.android.repackaged.com.sun.syndication.feed.WireFeed
Warning:org.springframework.http.converter.feed.AbstractWireFeedHttpMessageConverter: can't find referenced class com.google.code.rome.android.repackaged.com.sun.syndication.io.WireFeedOutput
Warning:org.springframework.http.converter.feed.AbstractWireFeedHttpMessageConverter: can't find referenced class com.google.code.rome.android.repackaged.com.sun.syndication.feed.WireFeed
Warning:org.springframework.http.converter.feed.AbstractWireFeedHttpMessageConverter: can't find referenced class com.google.code.rome.android.repackaged.com.sun.syndication.io.WireFeedInput
Warning:org.springframework.http.converter.feed.AbstractWireFeedHttpMessageConverter: can't find referenced class com.google.code.rome.android.repackaged.com.sun.syndication.io.FeedException
Warning:org.springframework.http.converter.feed.AbstractWireFeedHttpMessageConverter: can't find referenced class com.google.code.rome.android.repackaged.com.sun.syndication.feed.WireFeed
Warning:org.springframework.http.converter.feed.AbstractWireFeedHttpMessageConverter: can't find referenced class com.google.code.rome.android.repackaged.com.sun.syndication.io.WireFeedOutput
Warning:org.springframework.http.converter.feed.AbstractWireFeedHttpMessageConverter: can't find referenced class com.google.code.rome.android.repackaged.com.sun.syndication.feed.WireFeed
Warning:org.springframework.http.converter.feed.AbstractWireFeedHttpMessageConverter: can't find referenced class com.google.code.rome.android.repackaged.com.sun.syndication.io.FeedException
Warning:org.springframework.http.converter.feed.AbstractWireFeedHttpMessageConverter: can't find referenced class com.google.code.rome.android.repackaged.com.sun.syndication.io.WireFeedInput
Warning:org.springframework.http.converter.feed.AbstractWireFeedHttpMessageConverter: can't find referenced class com.google.code.rome.android.repackaged.com.sun.syndication.feed.WireFeed
Warning:org.springframework.http.converter.feed.AbstractWireFeedHttpMessageConverter: can't find referenced class com.google.code.rome.android.repackaged.com.sun.syndication.io.FeedException
Warning:org.springframework.http.converter.feed.AbstractWireFeedHttpMessageConverter: can't find referenced class com.google.code.rome.android.repackaged.com.sun.syndication.feed.WireFeed
Warning:org.springframework.http.converter.feed.AbstractWireFeedHttpMessageConverter: can't find referenced class com.google.code.rome.android.repackaged.com.sun.syndication.io.WireFeedOutput
Warning:org.springframework.http.converter.feed.AbstractWireFeedHttpMessageConverter: can't find referenced class com.google.code.rome.android.repackaged.com.sun.syndication.feed.WireFeed
Warning:org.springframework.http.converter.feed.AtomFeedHttpMessageConverter: can't find referenced class com.google.code.rome.android.repackaged.com.sun.syndication.feed.atom.Feed
Warning:org.springframework.http.converter.feed.RssChannelHttpMessageConverter: can't find referenced class com.google.code.rome.android.repackaged.com.sun.syndication.feed.rss.Channel
Warning:org.springframework.http.converter.feed.SyndFeedHttpMessageConverter: can't find referenced class com.google.code.rome.android.repackaged.com.sun.syndication.feed.synd.SyndFeed
Warning:org.springframework.http.converter.feed.SyndFeedHttpMessageConverter: can't find referenced class com.google.code.rome.android.repackaged.com.sun.syndication.io.SyndFeedInput
Warning:org.springframework.http.converter.feed.SyndFeedHttpMessageConverter: can't find referenced class com.google.code.rome.android.repackaged.com.sun.syndication.io.FeedException
Warning:org.springframework.http.converter.feed.SyndFeedHttpMessageConverter: can't find referenced class com.google.code.rome.android.repackaged.com.sun.syndication.feed.synd.SyndFeed
Warning:org.springframework.http.converter.feed.SyndFeedHttpMessageConverter: can't find referenced class com.google.code.rome.android.repackaged.com.sun.syndication.io.SyndFeedOutput
Warning:org.springframework.http.converter.feed.SyndFeedHttpMessageConverter: can't find referenced class com.google.code.rome.android.repackaged.com.sun.syndication.io.SyndFeedInput
Warning:org.springframework.http.converter.feed.SyndFeedHttpMessageConverter: can't find referenced class com.google.code.rome.android.repackaged.com.sun.syndication.io.FeedException
Warning:org.springframework.http.converter.feed.SyndFeedHttpMessageConverter: can't find referenced class com.google.code.rome.android.repackaged.com.sun.syndication.feed.synd.SyndFeed
Warning:org.springframework.http.converter.feed.SyndFeedHttpMessageConverter: can't find referenced class com.google.code.rome.android.repackaged.com.sun.syndication.io.SyndFeedOutput
Warning:org.springframework.http.converter.feed.SyndFeedHttpMessageConverter: can't find referenced class com.google.code.rome.android.repackaged.com.sun.syndication.feed.synd.SyndFeed
Warning:org.springframework.http.converter.feed.SyndFeedHttpMessageConverter: can't find referenced class com.google.code.rome.android.repackaged.com.sun.syndication.io.FeedException
Warning:org.springframework.http.converter.feed.SyndFeedHttpMessageConverter: can't find referenced class com.google.code.rome.android.repackaged.com.sun.syndication.io.SyndFeedInput
Warning:org.springframework.http.converter.feed.SyndFeedHttpMessageConverter: can't find referenced class com.google.code.rome.android.repackaged.com.sun.syndication.feed.synd.SyndFeed
Warning:org.springframework.http.converter.feed.SyndFeedHttpMessageConverter: can't find referenced class com.google.code.rome.android.repackaged.com.sun.syndication.io.FeedException
Warning:org.springframework.http.converter.feed.SyndFeedHttpMessageConverter: can't find referenced class com.google.code.rome.android.repackaged.com.sun.syndication.feed.synd.SyndFeed
Warning:org.springframework.http.converter.feed.SyndFeedHttpMessageConverter: can't find referenced class com.google.code.rome.android.repackaged.com.sun.syndication.io.SyndFeedOutput
Warning:org.springframework.http.converter.feed.SyndFeedHttpMessageConverter: can't find referenced class com.google.code.rome.android.repackaged.com.sun.syndication.feed.synd.SyndFeed
Warning:org.springframework.http.converter.json.GsonHttpMessageConverter: can't find referenced class com.google.gson.Gson
Warning:org.springframework.http.converter.json.GsonHttpMessageConverter: can't find referenced class com.google.gson.GsonBuilder
Warning:org.springframework.http.converter.json.GsonHttpMessageConverter: can't find referenced class com.google.gson.Gson
Warning:org.springframework.http.converter.json.GsonHttpMessageConverter: can't find referenced class com.google.gson.JsonSyntaxException
Warning:org.springframework.http.converter.json.GsonHttpMessageConverter: can't find referenced class com.google.gson.JsonIOException
Warning:org.springframework.http.converter.json.GsonHttpMessageConverter: can't find referenced class com.google.gson.JsonParseException
Warning:org.springframework.http.converter.json.GsonHttpMessageConverter: can't find referenced class com.google.gson.Gson
Warning:org.springframework.http.converter.json.GsonHttpMessageConverter: can't find referenced class com.google.gson.JsonSyntaxException
Warning:org.springframework.http.converter.json.GsonHttpMessageConverter: can't find referenced class com.google.gson.JsonIOException
Warning:org.springframework.http.converter.json.GsonHttpMessageConverter: can't find referenced class com.google.gson.JsonParseException
Warning:org.springframework.http.converter.json.GsonHttpMessageConverter: can't find referenced class com.google.gson.Gson
Warning:org.springframework.http.converter.json.GsonHttpMessageConverter: can't find referenced class com.google.gson.JsonSyntaxException
Warning:org.springframework.http.converter.json.GsonHttpMessageConverter: can't find referenced class com.google.gson.JsonIOException
Warning:org.springframework.http.converter.json.GsonHttpMessageConverter: can't find referenced class com.google.gson.JsonParseException
Warning:org.springframework.http.converter.json.GsonHttpMessageConverter: can't find referenced class com.google.gson.JsonIOException
Warning:org.springframework.http.converter.json.MappingJacksonHttpMessageConverter: can't find referenced class org.codehaus.jackson.map.ObjectMapper
Warning:org.springframework.http.converter.json.MappingJacksonHttpMessageConverter: can't find referenced class org.codehaus.jackson.JsonFactory
Warning:org.springframework.http.converter.json.MappingJacksonHttpMessageConverter: can't find referenced class org.codehaus.jackson.JsonGenerator
Warning:org.springframework.http.converter.json.MappingJacksonHttpMessageConverter: can't find referenced class org.codehaus.jackson.map.ObjectMapper
Warning:org.springframework.http.converter.json.MappingJacksonHttpMessageConverter: can't find referenced class org.codehaus.jackson.map.type.TypeFactory
Warning:org.springframework.http.converter.json.MappingJacksonHttpMessageConverter: can't find referenced class org.codehaus.jackson.JsonEncoding
Warning:org.springframework.http.converter.json.MappingJacksonHttpMessageConverter: can't find referenced class org.codehaus.jackson.type.JavaType
Warning:org.springframework.http.converter.json.MappingJacksonHttpMessageConverter: can't find referenced class org.codehaus.jackson.JsonEncoding
Warning:org.springframework.http.converter.json.MappingJacksonHttpMessageConverter: can't find referenced class org.codehaus.jackson.JsonGenerator
Warning:org.springframework.http.converter.json.MappingJacksonHttpMessageConverter: can't find referenced class org.codehaus.jackson.JsonEncoding
Warning:org.springframework.http.converter.json.MappingJacksonHttpMessageConverter: can't find referenced class org.codehaus.jackson.JsonFactory
Warning:org.springframework.http.converter.json.MappingJacksonHttpMessageConverter: can't find referenced class org.codehaus.jackson.JsonGenerator
Warning:org.springframework.http.converter.json.MappingJacksonHttpMessageConverter: can't find referenced class org.codehaus.jackson.map.type.TypeFactory
Warning:org.springframework.http.converter.json.MappingJacksonHttpMessageConverter: can't find referenced class org.codehaus.jackson.JsonEncoding
Warning:org.springframework.http.converter.json.MappingJacksonHttpMessageConverter: can't find referenced class org.codehaus.jackson.map.ObjectMapper
Warning:org.springframework.http.converter.json.MappingJacksonHttpMessageConverter: can't find referenced class org.codehaus.jackson.type.JavaType
Warning:org.springframework.http.converter.json.MappingJacksonHttpMessageConverter: can't find referenced class org.codehaus.jackson.JsonEncoding
Warning:org.springframework.http.converter.json.MappingJacksonHttpMessageConverter: can't find referenced class org.codehaus.jackson.JsonGenerator
Warning:org.springframework.http.converter.json.MappingJacksonHttpMessageConverter: can't find referenced class org.codehaus.jackson.type.JavaType
Warning:org.springframework.http.converter.json.MappingJacksonHttpMessageConverter: can't find referenced class org.codehaus.jackson.JsonEncoding
Warning:org.springframework.http.converter.xml.SimpleXmlHttpMessageConverter: can't find referenced class org.simpleframework.xml.core.Persister
Warning:org.springframework.http.converter.xml.SimpleXmlHttpMessageConverter: can't find referenced class org.simpleframework.xml.Root
Warning:org.springframework.http.converter.xml.SimpleXmlHttpMessageConverter: can't find referenced class org.simpleframework.xml.Serializer

**Comment by andreiverdes** [comment]
-keep class org.springframework.**
-keep class org.springframework.** { *; }
-keepnames class org.springframework.** { *; }
-keepclassmembers class org.springframework.** {*;}
-keepclassmembers enum org.springframework.** {*;}
-keepclassmembers interface org.springframework.** {*;}

**Comment by michel-t-86** [comment]
Thanks Andrei

**Comment by royclarkson** [comment]
Thanks for the help @andreiverdes!

**Comment by andreiverdes** [comment]
Glad to help :smile:

**Comment by sytolk** [comment]
this works for me
```
-keep class * implements android.os.Parcelable {
     public static final android.os.Parcelable$Creator *;
   }
 -keepclassmembers public class org.springframework {
     public *;
 }
```
