### ISSUE TITLE
Debug log print the sent requests/response

### ISSUE THREAD

**Issue by jclemus91** [spring-projects/spring-android#27]
Hi, can someone help me, amm I need to show logs of requests sent by my app

**Comment by andreiverdes** [comment]
restTemplate.setInterceptors(new ArrayList<ClientHttpRequestInterceptor>());
 restTemplate.getInterceptors().add(new ClientHttpRequestInterceptor(){
    @Override public ClientHttpResponse intercept(HttpRequest request, byte[] body, ClientHttpRequestExecution execution) throws IOException { 
ClientHttpResponse response = execution.execute(request, body);
//print response
return response
}});
Also, please consider closing this as it's not a project related issue. 
I recommend into using stackoverflow.com for such questions.

**Comment by royclarkson** [comment]
@andreiverdes thanks for the help!

**Comment by andreiverdes** [comment]
No problem!

**Comment by gunjan07** [comment]
Hey Guys ,

Can anyone help me to print the response that i get ?

I am using restemplate and AsyncClass for the server call

**Comment by andreiverdes** [comment]
AsyncClass?
The code for printing the response is described above. You can do `response.getBody()` and get the response as an `InputStream`, turn it into String and print it. :)
