### ISSUE TITLE
The newest SpringAndroid version is ? OkHttp support is not the newest ！

### ISSUE THREAD

**Issue by mrljdx** [spring-projects/spring-android#29]
Hi,
Recently i want to use SpringAndroid with OkHttp，but okHttp is updated at  'com.squareup.okhttp3:okhttp:3.0.0-RC1' , there is a big change in okHttp. but SpringAndroid 2.0.0M3 is still okHttp2.x version , can someone update the library ?

**Comment by WonderCsabo** [comment]
I think we should add a new request factory class and keep the old one, too. It is possible because OkHttp 3 has a new package name. @royclarkson what do you think?

**Comment by qazt482** [comment]
Is this project being maintained? I too am hoping for support of the latest OkHttp library but its sad to see no response.

**Comment by WonderCsabo** [comment]
@royclarkson can you check that the original Spring project has OkHttp3 support maybe (as i recall you imported the current OkHttp factory from there)? If it already does, we can easily import that here.

**Comment by royclarkson** [comment]
@WonderCsabo It's still on 2.7.4 https://github.com/spring-projects/spring-framework/blob/master/build.gradle#L67

**Comment by WonderCsabo** [comment]
Well, then we can adapt the [solution from Retrofit](https://github.com/square/retrofit/blob/master/retrofit/src/main/java/retrofit2/OkHttpCall.java).

**Comment by royclarkson** [comment]
Probably best to leave support for 2.x as is, and make a new `OkHttp3ClientHttpRequestFactory`.

**Comment by WonderCsabo** [comment]
https://github.com/spring-projects/spring-android/issues/29#issuecomment-171572219 :wink:

**Comment by royclarkson** [comment]
What you said. :)

**Comment by WonderCsabo** [comment]
@royclarkson thanks, i just tested this new factory and it indeed works!

**Comment by royclarkson** [comment]
@WonderCsabo great! thanks for the feedback.

**Comment by royclarkson** [comment]
2.0.0.M4 is now available in repo.spring.io. It has these latest changes.

```
dependencies {
    compile("org.springframework.android:spring-android-rest-template:2.0.0.M4")
}
repositories {
    maven { url "https://repo.spring.io/libs-milestone" }
}
```

**Comment by mrljdx** [comment]
@royclarkson  i add the dependecies and try compile gradle again,but shows as belows:
"Error:Could not find org.springframework.android:spring-android-rest-template:2.0.0.M4."

**Comment by WonderCsabo** [comment]
@mrljdx did you add the repo as well? Because the artifact is correctly deployed, so there is a problem at your end.

**Comment by royclarkson** [comment]
It's a milestone release, so it's not published to Maven Central.
