### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by PashaEagle** [spring-projects/spring-android#53]
Should I use it create new app?

**Comment by andreiverdes** [comment]
I would personally recommend Retrofit + Okhttp:

https://square.github.io/retrofit/
https://square.github.io/okhttp/

You'll find a bigger community and more common issues and responses rather than `spring-android`

**Comment by royclarkson** [comment]
Thanks for your interest in the project. However, this project is no longer active and has reached end of life.
